INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (1, 1, '2 × 35 + 12 + 1', false, 3, 83);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (2, 1, '62 - 35 + 69 - 10', false, 3, 86);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (3, 1, '57 + 11 - 21 + 30', false, 3, 77);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (4, 1, '75 - (9 - 31)', true, 2, 97);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (5, 1, '1 + (96 - 38)', true, 2, 59);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (6, 1, '7 × 8 + 91 - 75', false, 3, 72);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (7, 1, '70 - (3 + 9)', true, 2, 58);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (8, 1, '36 - 41 - 70 + 88', false, 3, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (9, 1, '(66 + 37) - 77', true, 2, 26);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (10, 1, '70 - (100 - 61)', true, 2, 31);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (11, 2, '59 ÷ 7 ÷ 2 + 3', false, 3, 7.21);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (12, 2, '(37 ÷ 95) ÷ 62', true, 2, 0.01);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (13, 2, '26 ÷ 9 + 84 ÷ 8', false, 3, 13.39);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (14, 2, '42 + 50 - 80 ÷ 10', false, 3, 84);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (15, 2, '60 - (68 ÷ 7)', true, 2, 50.29);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (16, 2, '29 ÷ (66 ÷ 22)', true, 2, 9.67);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (17, 2, '(28 ÷ 35) + 79', true, 2, 79.8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (18, 2, '15 - (97 ÷ 30)', true, 2, 11.77);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (19, 2, '15 + 88 ÷ 9 ÷ 4', false, 3, 17.44);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (20, 2, '79 + 59 - 31 - 63', false, 3, 44);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (21, 3, '1 + 17', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (22, 3, '8 + 4', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (23, 3, '3 + 11', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (24, 3, '9 + 11', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (25, 3, '16 - 11', false, 1, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (26, 3, '20 - 9', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (27, 3, '15 - 15', false, 1, 0);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (28, 3, '14 - 6', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (29, 3, '1 × 11', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (30, 3, '2 + 5', false, 1, 7);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (31, 4, '6 - 2', false, 1, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (32, 4, '11 - 10', false, 1, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (33, 4, '3 + 16', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (34, 4, '11 + 9', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (35, 4, '11 - 5', false, 1, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (36, 4, '2 + 15', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (37, 4, '17 - 10', false, 1, 7);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (38, 4, '1 + 6', false, 1, 7);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (39, 4, '7 + 12', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (40, 4, '17 - 8', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (41, 5, '16 - 6', false, 1, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (42, 5, '12 - 7', false, 1, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (43, 5, '17 - 9', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (44, 5, '20 - 10', false, 1, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (45, 5, '4 + 5', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (46, 6, '16 - 10', false, 1, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (47, 6, '17 + 5', false, 1, 22);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (48, 6, '4 + 7', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (49, 6, '25 - 25', false, 1, 0);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (50, 6, '16 - 6', false, 1, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (51, 12, '6 + 2', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (52, 12, '15 - 10', false, 1, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (53, 12, '16 - 15', false, 1, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (54, 12, '23 - 2', false, 1, 21);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (55, 12, '24 - 1', false, 1, 23);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (56, 12, '16 - 2', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (57, 12, '7 - 2', false, 1, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (58, 12, '8 + 8', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (59, 12, '13 + 11', false, 1, 24);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (60, 12, '18 - 14', false, 1, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (61, 15, '4 × 3', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (62, 15, '25 - 7', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (63, 15, '17 - 17', false, 1, 0);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (64, 15, '18 - 9', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (65, 15, '14 - 11', false, 1, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (66, 15, '5 + 15', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (67, 15, '(4 + 10) × 1', true, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (68, 15, '5 × 2', false, 1, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (69, 15, '9 + 10', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (70, 15, '21 - 6', false, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (71, 30, '20 - 18', false, 1, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (72, 30, '11 + 14', false, 1, 25);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (73, 30, '21 - 16', false, 1, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (74, 30, '5 + 6', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (75, 30, '15 - 6', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (76, 31, '16 - 8', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (77, 31, '1 + 13', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (78, 31, '2 + 16', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (79, 31, '22 - 10', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (80, 31, '1 + 16', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (81, 33, '19 - 4', false, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (82, 33, '11 - 7', false, 1, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (83, 33, '23 - 13', false, 1, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (84, 33, '8 + 9', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (85, 33, '17 - 13', false, 1, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (86, 37, '6 + 14', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (87, 37, '6 - 5', false, 1, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (88, 37, '6 + 3', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (89, 37, '3 - 3', false, 1, 0);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (90, 37, '24 - 6', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (91, 38, '10 + 11', false, 1, 21);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (92, 38, '4 + 6', false, 1, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (93, 38, '19 - 1', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (94, 38, '18 - 4', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (95, 38, '25 - 8', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (96, 39, '25 - 23', false, 1, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (97, 39, '11 + 4', false, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (98, 39, '13 - 13', true, 1, 0);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (99, 39, '17 - 5', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (100, 39, '21 - 11', false, 1, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (101, 40, '11 + 8', true, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (102, 40, '2 + 13', true, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (103, 40, '10 + 6', true, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (104, 40, '22 - 6', true, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (105, 40, '6 + 19', true, 1, 25);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (106, 41, '24 + 4', false, 1, 28);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (107, 41, '9 + 24', false, 1, 33);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (108, 41, '4 + 1', false, 1, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (109, 41, '1 + 1', false, 1, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (110, 41, '25 - 3', false, 1, 22);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (111, 42, '13 - 25', false, 1, -12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (112, 42, '10 - 11', false, 1, -1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (113, 42, '11 - 8', false, 1, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (114, 42, '10 + 6', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (115, 42, '19 + 7', false, 1, 26);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (116, 43, '3 - 5', false, 1, -2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (117, 43, '11 + 13', false, 1, 24);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (118, 43, '8 × 12', false, 1, 96);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (119, 43, '19 - (3 × 4)', true, 2, 7);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (120, 43, '20 - 1', true, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (121, 44, '(2 × 18) - 16', true, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (122, 44, '5 + (1 × 20)', true, 2, 25);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (123, 44, '(13 × 2) - 14', true, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (124, 44, '6 - 24', false, 1, -18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (125, 44, '16 × 21', false, 1, 336);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (126, 45, '12 - 14', false, 1, -2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (127, 45, '6 + 1', false, 1, 7);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (128, 45, '8 + 3', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (129, 45, '14 + 14', false, 1, 28);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (130, 45, '(3 - 1) × 8', true, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (131, 46, '(9 × 2) - 16', true, 2, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (132, 46, '11 + 12', true, 1, 23);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (133, 46, '(8 × 2) + 3', true, 2, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (134, 46, '(14 - 11) × 2', true, 2, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (135, 46, '(16 - 14) × 4', true, 2, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (136, 47, '(19 × 1) + 1', true, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (137, 47, '20 + 5', true, 1, 25);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (138, 47, '5 + (4 × 4)', true, 2, 21);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (139, 47, '15 + 5', true, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (140, 47, '1 × (2 × 1)', true, 2, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (141, 48, '(9 - 19) + 12', true, 2, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (142, 48, '(17 + 5) - 19', true, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (143, 48, '3 - (5 - 5)', true, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (144, 48, '(19 - 2) - 15', true, 2, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (145, 48, '23 - (18 + 1)', true, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (146, 49, '15 + (1 + 2)', true, 2, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (147, 49, '6 + (3 + 16)', true, 2, 25);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (148, 49, '17 + (2 + 2)', true, 2, 21);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (149, 49, '10 + 8 + 1', true, 2, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (150, 49, '(17 + 3) + 4', true, 2, 24);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (151, 50, '(5 - 1) - 3', true, 2, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (152, 50, '(7 + 17) - 12', true, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (153, 50, '8 + (8 - 10)', true, 2, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (154, 50, '(15 + 12) - 12', true, 2, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (155, 50, '23 - (16 - 17)', true, 2, 24);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (156, 51, '15 - 2', true, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (157, 51, '2 + 3', true, 1, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (158, 51, '4 + 21', true, 1, 25);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (159, 51, '3 + 1', true, 1, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (160, 51, '10 - 6', true, 1, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (161, 52, '17 - (1 × 12)', true, 2, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (162, 52, '(1 × 1) × 22', true, 2, 22);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (163, 52, '(3 × 8) - 16', true, 2, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (164, 52, '1 × 21', true, 1, 21);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (165, 52, '(7 × 2) - 2', true, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (166, 53, '(3 + 8) + 14', true, 2, 25);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (167, 53, '(12 + 2) + 2', true, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (168, 53, '25 - (2 + 17)', true, 2, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (169, 53, '(16 + 12) - 24', true, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (170, 53, '(23 - 6) - 5', true, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (171, 54, '4 + (11 - 2)', true, 2, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (172, 54, '(7 + 24) - 21', true, 2, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (173, 54, '4 - 8 + 22', false, 2, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (174, 54, '24 - 1 × 6', false, 2, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (175, 54, '7 + 25 - 11', false, 2, 21);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (176, 55, '7 - 15 + 23', false, 2, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (177, 55, '12 + (7 + 2)', true, 2, 21);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (178, 55, '9 × (1 + 1)', true, 2, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (179, 55, '18 - 1 - 10', false, 2, 7);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (180, 55, '21 - 1 × 8', false, 2, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (181, 56, '17 + (13 - 19)', true, 2, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (182, 56, '2 × 12 - 1', false, 2, 23);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (183, 56, '2 × 11 - 10', false, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (184, 56, '22 - 8 - 5', false, 2, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (185, 56, '6 + (8 + 7)', true, 2, 21);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (186, 57, '24 - 14 × 1', true, 2, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (187, 57, '5 × 4 × 1', false, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (188, 57, '5 + 9 - 2', false, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (189, 57, '(2 × 14) - 10', true, 2, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (190, 57, '3 × 8 - 3', false, 2, 21);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (191, 58, '16 - 5 - 2', false, 2, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (192, 58, '3 × 9 - 23', false, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (193, 58, '11 + 16 - 19', false, 2, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (194, 58, '(16 × 1) + 7', true, 2, 23);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (195, 58, '5 + 9 - 11', true, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (196, 59, '(9 × 5) - 23', true, 2, 22);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (197, 59, '22 × 1 - 10', false, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (198, 59, '16 + 21 - 21', false, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (199, 59, '(1 × 7) + 9', true, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (200, 59, '18 + 6 - 9', false, 2, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (201, 60, '21 - 19 + 8', false, 2, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (202, 60, '25 × 1 - 24', false, 2, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (203, 60, '2 × (19 - 11)', true, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (204, 60, '12 - 4 + 12', false, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (205, 60, '20 - 10 + 10', true, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (206, 61, '(3 × 4) + 2', true, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (207, 61, '(4 × 5) - 17', true, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (208, 61, '7 - 12 + 9', false, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (209, 61, '15 - 20 + 24', false, 2, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (210, 61, '2 - 18 + 16', false, 2, 0);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (211, 62, '(16 × 2) - 20', true, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (212, 62, '(3 × 4) - 10', true, 2, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (213, 62, '18 - 6 - 9', false, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (214, 62, '21 - 5 - 10', false, 2, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (215, 62, '16 - 7 + 9', false, 2, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (216, 63, '19 × (3 - 2)', true, 2, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (217, 63, '(8 × 2) - 2', true, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (218, 63, '12 × 1 - 2', false, 2, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (219, 63, '20 + 23 - 23', false, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (220, 63, '5 + 8 + 1', false, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (221, 63, '25 - 25 + 24', false, 2, 24);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (222, 63, '6 - 23 + 25', false, 2, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (223, 63, '5 × 6 - 12', false, 2, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (224, 63, '14 + 4 - 2', false, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (225, 63, '1 × (18 - 2)', true, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (226, 64, '12 + 17 - 6', false, 2, 23);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (227, 64, '6 × (13 - 10)', true, 2, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (228, 64, '3 + 18 - 18', false, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (229, 64, '12 + 11 - 22', false, 2, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (230, 64, '24 + 14 - 19', false, 2, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (231, 64, '(2 × 7) + 1', true, 2, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (232, 64, '4 × 11 - 24', false, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (233, 64, '18 - 20 + 12', false, 2, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (234, 64, '24 + 20 - 20', false, 2, 24);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (235, 64, '8 × (16 - 13)', true, 2, 24);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (236, 65, '24 - 3 - 15', false, 2, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (237, 65, '4 + 2 + 11', false, 2, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (238, 65, '(13 × 2) - 12', true, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (239, 65, '(3 × 6) - 9', true, 2, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (240, 65, '(3 × 8) - 10', true, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (241, 66, '13 + 10 - 20', false, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (242, 66, '23 - 19 + 10', false, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (243, 66, '2 - 6 + 15', false, 2, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (244, 66, '5 × (4 + 1)', true, 2, 25);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (245, 66, '3 × (22 - 19)', true, 2, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (246, 67, '14 + 2 ÷ 4', false, 2, 14.5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (247, 67, '1 + 11 - 12', false, 2, 0);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (248, 67, '2 + 14 + 4', false, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (249, 67, '12 ÷ (21 - 17)', true, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (250, 67, '(24 × 4) ÷ 12', true, 2, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (251, 68, '1 + 16', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (252, 68, '4 + 5', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (253, 68, '5 - 3', false, 1, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (254, 68, '12 ÷ 4', false, 1, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (255, 68, '13 - 4', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (256, 69, '6 ÷ 2', false, 1, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (257, 69, '15 ÷ 9', false, 1, 1.67);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (258, 69, '25 ÷ 6', false, 1, 4.17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (259, 69, '16 ÷ 2', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (260, 69, '11 × 2', false, 1, 22);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (261, 70, '10 + 3', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (262, 70, '5 + 4', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (263, 70, '16 - 9', false, 1, 7);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (264, 70, '3 ÷ 7', false, 1, 0.43);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (265, 70, '16 - 5', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (266, 71, '9 ÷ 8', false, 1, 1.12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (267, 71, '18 ÷ 9', false, 1, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (268, 71, '11 × 1', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (269, 71, '3 + 10', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (270, 71, '15 + 4', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (271, 72, '1 ÷ 10', false, 1, 0.1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (272, 72, '11 - 4', false, 1, 7);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (273, 72, '1 ÷ 5', false, 1, 0.2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (274, 72, '18 ÷ 6', false, 1, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (275, 72, '19 ÷ 5', false, 1, 3.8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (276, 73, '2 + 18', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (277, 73, '4 + 14', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (278, 73, '2 + 14', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (279, 73, '19 - 6', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (280, 73, '9 - 9', false, 1, 0);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (281, 74, '7 + 6', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (282, 74, '9 - 8', false, 1, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (283, 74, '1 + 7', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (284, 74, '10 - 7', false, 1, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (285, 74, '12 + 1', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (286, 75, '1 × 13 - 8', false, 2, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (287, 75, '(5 × 5) - 13', true, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (288, 75, '18 - 15 + 7', false, 2, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (289, 75, '13 - 12 + 17', false, 2, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (290, 75, '(12 × 3) - 20', true, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (291, 76, '5 + 13 - 3', false, 2, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (292, 76, '9 + 6 - 11', false, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (293, 76, '4 × (7 - 6)', true, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (294, 76, '(5 × 2) - 5', true, 2, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (295, 76, '6 + 5 - 10', false, 2, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (296, 77, '(10 × 2) - 11', true, 2, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (297, 77, '10 - 1 + 3', false, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (298, 77, '(3 × 4) + 7', true, 2, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (299, 77, '15 - 4 + 8', false, 2, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (300, 77, '2 × 8 - 15', false, 2, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (301, 78, '14 × 2 - 12', false, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (302, 78, '(6 × 3) + 2', true, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (303, 78, '1 + 1 × 5', false, 2, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (304, 78, '5 × (3 + 1)', true, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (305, 78, '9 - 2 + 10', false, 2, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (306, 78, '14 + 10 - 13', false, 2, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (307, 78, '4 × 3 + 1', false, 2, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (308, 78, '1 + 12 + 2', false, 2, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (309, 78, '7 + 18 - 14', false, 2, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (310, 78, '5 + 2 × 5', false, 2, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (311, 79, '9 - 8 - 1', false, 2, 0);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (312, 79, '12 - 1 × 10', false, 2, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (313, 79, '18 - 18 + 11', false, 2, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (314, 79, '10 - 10 + 6', false, 2, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (315, 79, '15 + 5 - 16', false, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (316, 79, '1 + 12 - 12', false, 2, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (317, 79, '6 × 3 - 15', false, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (318, 79, '8 - 11 + 14', false, 2, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (319, 79, '5 + 6 - 6', false, 2, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (320, 79, '15 - 10 + 10', false, 2, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (321, 80, '8 - 1 × 4', false, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (322, 80, '5 + 9 + 6', false, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (323, 80, '6 - 11 + 16', false, 2, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (324, 80, '6 + 2 × 5', false, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (325, 80, '10 + 2 × 2', false, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (326, 80, '12 + 4 - 12', false, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (327, 80, '18 + 6 - 11', false, 2, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (328, 80, '1 × 3 + 3', false, 2, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (329, 80, '7 × 2 - 1', false, 2, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (330, 80, '11 + 7 - 12', false, 2, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (331, 81, '1 + 12 - 10', false, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (332, 81, '10 + 16 - 20', false, 2, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (333, 81, '1 + 14 - 7', false, 2, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (334, 81, '3 - 8 + 12', false, 2, 7);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (335, 81, '10 - 7 + 14', false, 2, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (336, 81, '15 × 2 - 18', false, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (337, 81, '3 × 8 - 5', false, 2, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (338, 81, '8 + 5 - 10', false, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (339, 81, '15 + 8 - 14', false, 2, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (340, 81, '1 × 2 - 1', false, 2, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (341, 82, '5 × 8 - 20', false, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (342, 82, '7 × 3 - 13', false, 2, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (343, 82, '3 + 18 - 5', false, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (344, 82, '13 + 17 - 18', false, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (345, 82, '2 - 7 + 19', false, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (346, 82, '6 + 6 + 7', false, 2, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (347, 82, '18 - 1 × 10', false, 2, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (348, 82, '8 - 3 × 2', false, 2, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (349, 82, '7 + 15 - 13', false, 2, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (350, 82, '15 - 17 + 4', false, 2, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (351, 83, '2 × (9 - 8)', true, 2, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (352, 83, '(8 × 3) - 5', true, 2, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (353, 83, '11 - 10 + 14', false, 2, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (354, 83, '(3 × 7) - 7', true, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (355, 83, '(7 × 3) - 10', true, 2, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (356, 83, '6 + 20 - 13', false, 2, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (357, 83, '7 - 1 × 4', false, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (358, 83, '2 + 3 + 13', false, 2, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (359, 83, '2 × 3 - 6', false, 2, 0);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (360, 83, '(9 × 2) - 5', true, 2, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (361, 84, '9 - 4 × 2', false, 2, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (362, 84, '(2 × 8) - 2', true, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (363, 84, '(2 × 3) - 3', true, 2, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (364, 84, '5 × (8 - 7)', true, 2, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (365, 84, '4 + 8 + 2', false, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (366, 84, '18 + 7 - 11', false, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (367, 84, '13 - 19 + 16', false, 2, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (368, 84, '(2 × 5) + 4', true, 2, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (369, 84, '(2 × 9) - 8', true, 2, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (370, 84, '16 - 20 + 5', false, 2, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (371, 85, '(7 × 2) + 3', true, 2, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (372, 85, '5 - 9 + 17', false, 2, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (373, 85, '16 - 19 + 7', false, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (374, 85, '(3 × 5) + 5', true, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (375, 85, '12 + 9 - 5', false, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (376, 85, '7 - 4 - 2', false, 2, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (377, 85, '(5 × 6) - 14', true, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (378, 85, '2 × 2 + 5', false, 2, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (379, 85, '4 × (4 - 3)', true, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (380, 85, '(2 × 8) - 3', true, 2, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (381, 86, '8 - 14 + 18', false, 2, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (382, 86, '(3 × 7) - 6', true, 2, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (383, 86, '4 × (3 + 2)', true, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (384, 86, '8 - 6 + 8', false, 2, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (385, 86, '11 - 5 × 2', false, 2, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (386, 86, '(2 × 5) - 6', true, 2, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (387, 86, '19 + 7 - 13', false, 2, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (388, 86, '18 + 20 - 18', false, 2, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (389, 86, '6 × (5 - 2)', true, 2, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (390, 86, '(2 × 10) - 4', true, 2, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (391, 87, '16 - 6', false, 1, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (392, 87, '5 + 8', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (393, 87, '8 + 7', false, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (394, 87, '2 × 7', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (395, 87, '13 + 7', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (396, 87, '5 + 11', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (397, 87, '11 - 7', false, 1, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (398, 87, '2 + 15', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (399, 87, '2 + 4', false, 1, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (400, 87, '20 - 15', false, 1, 5);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (401, 88, '17 + 2', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (402, 88, '9 + 8', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (403, 88, '12 - 9', false, 1, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (404, 88, '3 + 10', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (405, 88, '2 × 5', false, 1, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (406, 88, '17 - 3', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (407, 88, '10 + 7', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (408, 88, '3 + 4', false, 1, 7);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (409, 88, '10 - 9', false, 1, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (410, 88, '8 + 3', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (411, 89, '20 - 11', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (412, 89, '5 + 13', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (413, 89, '18 - 5', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (414, 89, '5 + 3', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (415, 89, '7 + 13', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (416, 89, '15 - 5', false, 1, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (417, 89, '6 + 13', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (418, 89, '20 - 12', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (419, 89, '9 - 7', false, 1, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (420, 89, '15 - 4', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (421, 90, '9 × 2', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (422, 90, '12 + 5', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (423, 90, '8 + 8', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (424, 90, '7 + 7', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (425, 90, '10 - 4', false, 1, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (426, 90, '20 - 8', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (427, 90, '2 + 13', false, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (428, 90, '12 + 3', false, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (429, 90, '14 + 6', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (430, 90, '5 + 11', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (431, 91, '12 + 2', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (432, 91, '3 + 11', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (433, 91, '12 + 7', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (434, 91, '6 + 10', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (435, 91, '9 + 2', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (436, 91, '5 + 3', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (437, 91, '5 + 14', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (438, 91, '7 + 11', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (439, 91, '9 + 4', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (440, 91, '7 + 5', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (441, 92, '14 + 6', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (442, 92, '12 + 8', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (443, 92, '4 × 3', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (444, 92, '2 + 10', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (445, 92, '6 + 8', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (446, 92, '5 + 3', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (447, 92, '9 + 9', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (448, 92, '4 × 5', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (449, 92, '9 + 2', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (450, 92, '6 + 2', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (451, 93, '11 + 3', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (452, 93, '6 + 2', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (453, 93, '9 + 3', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (454, 93, '5 + 10', false, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (455, 93, '4 + 5', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (456, 93, '9 + 7', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (457, 93, '7 × 2', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (458, 93, '7 + 13', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (459, 93, '2 + 12', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (460, 93, '7 + 4', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (461, 94, '2 × 7', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (462, 94, '8 × 2', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (463, 94, '6 × 2', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (464, 94, '3 × 4', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (465, 94, '9 + 7', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (466, 94, '7 + 5', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (467, 94, '17 + 2', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (468, 94, '7 + 6', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (469, 94, '14 + 4', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (470, 94, '5 + 10', false, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (471, 95, '3 × 2', false, 1, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (472, 95, '3 × 5', false, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (473, 95, '5 × 4', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (474, 95, '4 × 5', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (475, 95, '10 × 2', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (476, 95, '4 × 3', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (477, 95, '3 × 6', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (478, 95, '2 × 10', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (479, 95, '6 × 3', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (480, 95, '2 × 4', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (481, 96, '2 × 10', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (482, 96, '3 × 5', false, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (483, 96, '6 × 3', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (484, 96, '10 × 2', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (485, 96, '2 × 3', false, 1, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (486, 96, '3 × 4', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (487, 96, '9 × 2', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (488, 96, '4 × 5', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (489, 96, '2 × 8', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (490, 96, '3 × 2', false, 1, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (491, 97, '5 × 2', false, 1, 10);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (492, 97, '3 × 2', false, 1, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (493, 97, '2 × 8', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (494, 97, '5 × 4', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (495, 97, '3 × 3', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (496, 97, '2 × 9', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (497, 97, '4 × 2', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (498, 97, '7 × 2', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (499, 97, '6 × 3', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (500, 97, '6 × 2', false, 1, 12);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (501, 98, '16 - 12', false, 1, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (502, 98, '4 - 2', false, 1, 2);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (503, 98, '17 - 11', false, 1, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (504, 98, '4 - 3', false, 1, 1);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (505, 98, '19 - 11', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (506, 98, '18 - 9', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (507, 98, '16 - 7', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (508, 98, '13 - 13', false, 1, 0);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (509, 98, '5 - 2', false, 1, 3);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (510, 98, '17 - 13', false, 1, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (511, 99, '2 + 18', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (512, 99, '6 + 3', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (513, 99, '5 + 3', false, 1, 8);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (514, 99, '5 + 14', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (515, 99, '16 + 4', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (516, 99, '8 + 6', false, 1, 14);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (517, 99, '4 + 13', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (518, 99, '3 + 15', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (519, 99, '8 + 11', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (520, 99, '12 + 5', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (521, 100, '9 + 11', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (522, 100, '8 + 11', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (523, 100, '14 + 6', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (524, 100, '5 + 12', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (525, 100, '6 + 7', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (526, 100, '3 + 3', false, 1, 6);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (527, 100, '7 + 6', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (528, 100, '14 + 4', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (529, 100, '2 + 13', false, 1, 15);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (530, 100, '10 + 9', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (531, 100, '6 + 14', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (532, 100, '12 + 6', false, 1, 18);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (533, 100, '15 + 2', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (534, 100, '6 + 3', false, 1, 9);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (535, 100, '15 + 4', false, 1, 19);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (536, 101, '3 + 8', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (537, 101, '14 + 6', false, 1, 20);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (538, 101, '2 + 11', false, 1, 13);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (539, 101, '13 + 3', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (540, 101, '5 + 6', false, 1, 11);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (541, 102, '2 + 2', false, 1, 4);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (542, 102, '10 + 6', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (543, 102, '4 + 13', false, 1, 17);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (544, 102, '4 + 12', false, 1, 16);
INSERT INTO ks_db.expression (expression_id, exercise_set_id, expression_text, has_brackets, operator_count, answer) VALUES (545, 102, '7 + 10', false, 1, 17);
